
x-constraints:
  APPLICATION_ROOT_DIRECTORY: &ROOT_DIRECTORY "."

x-APPLICATION_ENVIRONMENT: &ENV
  DEBUG: ${DEBUG}
  LOG_LEVEL: ${LOG_LEVEL}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}
  DATABASE_NAME: ${DATABASE_NAME}

x-DEVELOPMENT_VOLUMES: &DEVELOPMENT_VOLUMES
  - ./alembic:/app/alembic
  - ./resources/logs:/app/resources/logs
  - ./src:/app/src:ro

networks:
  app:
    driver: bridge

volumes:
  database:
  nats:
  
services:
  api:
    build:
      dockerfile: "./resources/docker/api.dockerfile"
      context: *ROOT_DIRECTORY
    environment: *ENV
    volumes: *DEVELOPMENT_VOLUMES
    networks:
      - app
    depends_on:
      - database
    ports:
      - "8000:8000"
    restart: unless-stopped

  database:
    image: postgres:17.6
    networks:
      - app
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_NAME}"]
      interval: 7s
      timeout: 5s
      retries: 2
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
