name: CI

on:
  push:
  pull_request:

jobs:
  push-images:
    needs: [test, lint, lint-type]
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
       - name: Echo Implementation
         run: | 
          echo "TODO: Push Images to Habor or DockerHUB later."

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:17.6
        env:
          POSTGRES_DB: database
          POSTGRES_USER: database
          POSTGRES_PASSWORD: database

      broker:
        image: rabbitmq:4.2.2-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
          python-version: 3.12

      - name: Install Dependencies
        run: uv sync --all-groups

      - name: Run Linters
        run: uv run pytest --maxfail=1 --disable-warnings -q
  
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
          python-version: 3.12

      - name: Install Dependencies
        run: uv sync --group linters

      - name: Run Linters
        run: uv run ruff check .

  lint-type:
    name: Lint Type
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
          python-version: 3.12

      - name: Install Dependencies
        run: uv sync --group linters --group app

      - name: Run Linters
        run: uv run pyright
